### ISSUE TITLE
Redirect Error 

### ISSUE THREAD

**Issue by rafaelmagic** [louy/photo-swipe#1]
photo-swipe.php

FIX:
Line 41:
plugin_dir_url( **FILE** ) . 'lib/default-skin/default-skin.css ',

Change to:
plugin_dir_url( **FILE** ) . 'lib/default-skin/default-skin.css',

Causing a redirect error

**Comment by rafaelmagic** [comment]
Causing redirect error

**Comment by louy** [comment]
Fixed in **4.1.1.1**. Thanks for spotting!
