### ISSUE TITLE
Not working on Category Page

### ISSUE THREAD

**Issue by rafaelmagic** [louy/photo-swipe#2]
Not working on Category Page:

In photo-swipe.php, line 12
change
if( is_singular() )
to
if( !is_admin() )

https://wordpress.org/support/topic/not-working-on-category-page

**Comment by louy** [comment]
I didn't think anyone would want this in archive pages, but it makes sense to me. I'll update shortly.

**Comment by louy** [comment]
Fixed in **4.1.1.1**.
